"""Annual tax report data + HTML rendering (plan Sec. 15, first version).

Sprint 2 minimal report: annual summary, per-disposal table, classification
note (default goede_huisvader; classifier arrives Sprint 7), disclaimer.
Print-optimised CSS is inline so the artifact is a single self-contained file.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from decimal import Decimal
from pathlib import Path

import jinja2

from utxoproof import __version__
from utxoproof.belgian_tax import COMMUNAL_SURCHARGE_DEFAULT, apply_belgian_tax
from utxoproof.cli import compute_details

DISCLAIMER = (
    "This report is generated by utxoproof and is a computational aid. "
    "It does not constitute professional tax advice. All figures should be "
    "verified with a certified Belgian tax adviser (fiscaal adviseur / "
    "conseiller fiscal) before filing your annual tax return (aangifte "
    "personenbelasting / declaration a l'impot des personnes physiques). "
    "The goede huisvader / speculator classification is a heuristic estimate "
    "based on observable on-chain and exchange data; the final classification "
    "is determined by SPF Finances on the basis of all facts and circumstances."
)


@dataclass
class DisposalRow:
    date: str
    btc: Decimal
    eur_per_btc: Decimal
    proceeds_eur: Decimal
    cost_basis_eur: Decimal
    gain_eur: Decimal
    tax_eur: Decimal


@dataclass
class TaxReport:
    year: int
    generated_at: str
    version: str
    method: str
    classification: str
    communal_rate: Decimal
    disposals: list[DisposalRow] = field(default_factory=list)
    gain_eur: Decimal = Decimal("0")
    tax_eur: Decimal = Decimal("0")
    communal_eur: Decimal = Decimal("0")
    total_eur: Decimal = Decimal("0")


def build_report(
    csv_path: str | Path,
    year: int,
    communal_rate: Decimal = COMMUNAL_SURCHARGE_DEFAULT,
) -> TaxReport:
    """Build report data with per-disposal Belgian tax (goede huisvader)."""
    details = compute_details(csv_path, year)
    rows = []
    for d in details["disposals"]:
        tax = apply_belgian_tax(d["gain_eur"], "goede_huisvader", communal_rate)
        rows.append(
            DisposalRow(
                date=d["date"],
                btc=d["btc"],
                eur_per_btc=d["eur_per_btc"],
                proceeds_eur=d["proceeds_eur"],
                cost_basis_eur=d["cost_basis_eur"],
                gain_eur=d["gain_eur"],
                tax_eur=tax["tax_eur"],
            )
        )
    gain = details["gain_loss_eur"]
    total_tax = apply_belgian_tax(gain, "goede_huisvader", communal_rate)
    return TaxReport(
        year=year,
        generated_at=datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC"),
        version=__version__,
        method="moving_average",
        classification="goede_huisvader (default; classifier arrives in Sprint 7)",
        communal_rate=communal_rate,
        disposals=rows,
        gain_eur=gain,
        tax_eur=total_tax["tax_eur"],
        communal_eur=total_tax["communal_surcharge_eur"],
        total_eur=total_tax["total_eur"],
    )


def _template() -> jinja2.Template:
    text = (Path(__file__).parent / "templates" / "tax_report.html.j2").read_text(encoding="utf-8")
    return jinja2.Environment(autoescape=True).from_string(text)


def _fmt(v: Decimal) -> str:
    return f"{v:.2f}"


def render_report(report: TaxReport) -> str:
    """Render the HTML report. Numbers are preformatted (2dp) for the template."""
    return _template().render(
        year=report.year,
        generated_at=report.generated_at,
        version=report.version,
        method=report.method,
        classification=report.classification,
        communal_rate=f"{(report.communal_rate * 100):.2f}%",
        disposals=[
            {
                "date": r.date,
                "btc": f"{r.btc:.8f}",
                "eur_per_btc": _fmt(r.eur_per_btc),
                "proceeds_eur": _fmt(r.proceeds_eur),
                "cost_basis_eur": _fmt(r.cost_basis_eur),
                "gain_eur": _fmt(r.gain_eur),
                "tax_eur": _fmt(r.tax_eur),
            }
            for r in report.disposals
        ],
        disposal_count=len(report.disposals),
        gain_eur=_fmt(report.gain_eur),
        tax_eur=_fmt(report.tax_eur),
        communal_eur=_fmt(report.communal_eur),
        total_eur=_fmt(report.total_eur),
        disclaimer=DISCLAIMER,
    )


def write_report(
    csv_path: str | Path,
    year: int,
    out_dir: str | Path,
    communal_rate: Decimal = COMMUNAL_SURCHARGE_DEFAULT,
) -> Path:
    """Build + render + write ``report.html`` into ``out_dir``. Returns the path."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    target = out / "report.html"
    target.write_text(
        render_report(build_report(csv_path, year, communal_rate)),
        encoding="utf-8",
    )
    return target
