"""Annual tax report data + HTML rendering (plan Sec. 15, first version).

Sprint 2 minimal report: annual summary, per-disposal table, classification
note (default goede_huisvader; classifier arrives Sprint 7), disclaimer.
Print-optimised CSS is inline so the artifact is a single self-contained file.
"""

from __future__ import annotations

import datetime
import sqlite3
from collections.abc import Callable
from dataclasses import dataclass, field
from decimal import Decimal
from pathlib import Path

import jinja2

from utxoproof import __version__
from utxoproof.advisory import UTXOAdvisory, portfolio_summary
from utxoproof.belgian_tax import COMMUNAL_SURCHARGE_DEFAULT, apply_belgian_tax
from utxoproof.cli import compute_details
from utxoproof.config import ClassifierConfig

DISCLAIMER = (
    "This report is generated by utxoproof and is a computational aid. "
    "It does not constitute professional tax advice. All figures should be "
    "verified with a certified Belgian tax adviser (fiscaal adviseur / "
    "conseiller fiscal) before filing your annual tax return (aangifte "
    "personenbelasting / declaration a l'impot des personnes physiques). "
    "The goede huisvader / speculator classification is a heuristic estimate "
    "based on observable on-chain and exchange data; the final classification "
    "is determined by SPF Finances on the basis of all facts and circumstances."
)


@dataclass
class DisposalRow:
    date: str
    btc: Decimal
    eur_per_btc: Decimal
    proceeds_eur: Decimal
    cost_basis_eur: Decimal
    gain_eur: Decimal
    tax_eur: Decimal


@dataclass
class TaxReport:
    year: int
    generated_at: str
    version: str
    method: str
    classification: str
    rationale: str
    communal_rate: Decimal
    disposals: list[DisposalRow] = field(default_factory=list)
    gain_eur: Decimal = Decimal("0")
    tax_eur: Decimal = Decimal("0")
    communal_eur: Decimal = Decimal("0")
    total_eur: Decimal = Decimal("0")


def build_report(
    csv_path: str | Path,
    year: int,
    communal_rate: Decimal = COMMUNAL_SURCHARGE_DEFAULT,
    classifier_cfg: ClassifierConfig | None = None,
) -> TaxReport:
    """Build report data with per-disposal Belgian tax + classification."""
    from utxoproof.classifier import BelgianClassifier, signals_from_csv

    cfg = classifier_cfg or ClassifierConfig()
    signals = signals_from_csv(csv_path, year, cfg)
    tax_class, rationale = BelgianClassifier(
        cfg.speculator_threshold, cfg.passive_threshold
    ).classify(signals)
    classification = tax_class.value
    details = compute_details(csv_path, year)
    rows = []
    for d in details["disposals"]:
        tax = apply_belgian_tax(d["gain_eur"], classification, communal_rate)
        rows.append(
            DisposalRow(
                date=d["date"],
                btc=d["btc"],
                eur_per_btc=d["eur_per_btc"],
                proceeds_eur=d["proceeds_eur"],
                cost_basis_eur=d["cost_basis_eur"],
                gain_eur=d["gain_eur"],
                tax_eur=tax["tax_eur"],
            )
        )
    gain = details["gain_loss_eur"]
    total_tax = apply_belgian_tax(gain, classification, communal_rate)
    return TaxReport(
        year=year,
        generated_at=datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC"),
        version=__version__,
        method="moving_average",
        classification=classification,
        rationale=rationale,
        communal_rate=communal_rate,
        disposals=rows,
        gain_eur=gain,
        tax_eur=total_tax["tax_eur"],
        communal_eur=total_tax["communal_surcharge_eur"],
        total_eur=total_tax["total_eur"],
    )


def _template() -> jinja2.Template:
    text = (Path(__file__).parent / "templates" / "tax_report.html.j2").read_text(encoding="utf-8")
    return jinja2.Environment(autoescape=True).from_string(text)


def _fmt(v: Decimal) -> str:
    return f"{v:.2f}"


def render_report(report: TaxReport) -> str:
    """Render the HTML report. Numbers are preformatted (2dp) for the template."""
    return _template().render(
        year=report.year,
        generated_at=report.generated_at,
        version=report.version,
        method=report.method,
        classification=report.classification,
        classification_label=report.classification.replace("_", " "),
        rationale=report.rationale,
        is_speculator=report.classification == "speculator",
        communal_rate=f"{(report.communal_rate * 100):.2f}%",
        disposals=[
            {
                "date": r.date,
                "btc": f"{r.btc:.8f}",
                "eur_per_btc": _fmt(r.eur_per_btc),
                "proceeds_eur": _fmt(r.proceeds_eur),
                "cost_basis_eur": _fmt(r.cost_basis_eur),
                "gain_eur": _fmt(r.gain_eur),
                "tax_eur": _fmt(r.tax_eur),
            }
            for r in report.disposals
        ],
        disposal_count=len(report.disposals),
        gain_eur=_fmt(report.gain_eur),
        tax_eur=_fmt(report.tax_eur),
        communal_eur=_fmt(report.communal_eur),
        total_eur=_fmt(report.total_eur),
        disclaimer=DISCLAIMER,
    )


def write_report(
    csv_path: str | Path,
    year: int,
    out_dir: str | Path,
    communal_rate: Decimal = COMMUNAL_SURCHARGE_DEFAULT,
    classifier_cfg: ClassifierConfig | None = None,
) -> Path:
    """Build + render + write ``report.html`` into ``out_dir``. Returns the path."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    target = out / "report.html"
    target.write_text(
        render_report(build_report(csv_path, year, communal_rate, classifier_cfg)),
        encoding="utf-8",
    )
    return target


# BIP84 spec-vector account (m/84'/0'/0', worthless test key).
DESCRIPTORS_DEMO_XPUB = (
    "zpub6rFR7y4Q2AijBEqTUquhVz398htDFrtymD9xYYfG1m4wAcvPhXNfE3EfH1r1ADqtfSdVCTo"
    "UG868RvUUkgDKf31mGDtKsAYz2oz2AGutZYs"
)
DESCRIPTORS_DEMO_FINGERPRINT = "73c5da0a"


def write_descriptors_page(out_dir: str | Path) -> Path:
    """Render the descriptor/address check page into ``out_dir``."""
    from utxoproof.descriptors import build_descriptors, derive_addresses

    descriptors = build_descriptors(DESCRIPTORS_DEMO_XPUB, DESCRIPTORS_DEMO_FINGERPRINT, 84, 0, 0)
    rows = [
        {"path": f"m/84'/0'/0'/0/{i}", "address": addr}
        for i, addr in enumerate(derive_addresses(DESCRIPTORS_DEMO_XPUB, 0, 0, 3))
    ]
    rows.append(
        {
            "path": "m/84'/0'/0'/1/0",
            "address": derive_addresses(DESCRIPTORS_DEMO_XPUB, 1, 0, 1)[0],
        }
    )
    template = jinja2.Environment(autoescape=True).from_string(
        (Path(__file__).parent / "templates" / "descriptors.html.j2").read_text(encoding="utf-8")
    )
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    target = out / "descriptors.html"
    target.write_text(
        template.render(
            xpub=DESCRIPTORS_DEMO_XPUB,
            fingerprint=DESCRIPTORS_DEMO_FINGERPRINT,
            external=descriptors["external"],
            change=descriptors["change"],
            addresses=rows,
        ),
        encoding="utf-8",
    )
    return target


def write_status_page(
    csv_path: str | Path,
    price_eur: Decimal,
    price_note: str,
    out_dir: str | Path,
) -> Path:
    """Render the holdings status page into ``out_dir``."""
    from utxoproof.cli import compute_status

    status = compute_status(csv_path, price_eur)
    template = jinja2.Environment(autoescape=True).from_string(
        (Path(__file__).parent / "templates" / "status.html.j2").read_text(encoding="utf-8")
    )
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    target = out / "status.html"
    target.write_text(
        template.render(
            as_of=datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC"),
            price_eur=f"{price_eur:.2f}",
            price_note=price_note,
            btc=f"{status['btc']:.8f}",
            cost_eur=f"{status['cost_eur']:.2f}",
            avg_cost_eur=f"{status['avg_cost_eur']:.2f}",
            value_eur=f"{status['value_eur']:.2f}",
            unrealized_eur=f"{status['unrealized_eur']:.2f}",
            disclaimer=DISCLAIMER,
        ),
        encoding="utf-8",
    )
    return target


def write_privacy_page(db: sqlite3.Connection, out_dir: str | Path) -> Path:
    """Run KYC seeding + propagation, then render the privacy page."""
    from utxoproof.kyc import detect_mixing_events, kyc_summary, propagate_graph, seed_source_kyc

    seed_source_kyc(db)
    propagate_graph(db)
    summary = kyc_summary(db)
    events = detect_mixing_events(db)
    template = jinja2.Environment(autoescape=True).from_string(
        (Path(__file__).parent / "templates" / "privacy.html.j2").read_text(encoding="utf-8")
    )
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    target = out / "privacy.html"
    target.write_text(
        template.render(
            generated_at=datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC"),
            version=__version__,
            summary=[
                {"status": s, "count": summary[s]} for s in ("kyc", "non_kyc", "mixed", "unknown")
            ],
            events=[
                {
                    "txid": str(e["txid"]),
                    "inputs": e["inputs"],
                    "kyc_inputs": e["kyc_inputs"],
                    "non_kyc_inputs": e["non_kyc_inputs"],
                    "value_sat": e["value_sat"],
                    "originating": e["originating"],
                }
                for e in events
            ],
            disclaimer=DISCLAIMER,
        ),
        encoding="utf-8",
    )
    return target


def write_advisory_page(
    advisories: list[UTXOAdvisory],
    current_price_eur: Decimal,
    price_note: str,
    as_of: str,
    out_dir: str | Path,
) -> Path:
    """Render the per-UTXO advisory table into ``out_dir``."""
    summary = portfolio_summary(advisories)
    template = jinja2.Environment(autoescape=True).from_string(
        (Path(__file__).parent / "templates" / "advisory.html.j2").read_text(encoding="utf-8")
    )
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    target = out / "advisory.html"
    target.write_text(
        template.render(
            as_of=as_of,
            current_price_eur=f"{current_price_eur:.2f}",
            price_note=price_note,
            advisories=[
                {
                    "utxo": f"{a.txid}:{a.vout}",
                    "btc": f"{a.amount_btc:.8f}",
                    "holding_days": a.holding_days,
                    "cost_eur": f"{a.acquisition_cost_eur:.2f}",
                    "value_eur": f"{a.current_value_eur:.2f}",
                    "gain_eur": f"{a.unrealized_gain_eur:.2f}",
                    "tax_eur": f"{a.tax_if_sold_eur:.2f}",
                    "kyc": a.kyc_status,
                    "flags": ",".join(sorted(f.value for f in a.flags)),
                }
                for a in advisories
            ],
            total_tax_eur=f"{summary['total_tax_eur']:.2f}",
            estate_value_eur=f"{summary['estate_value_eur']:.2f}",
            borrow_value_eur=f"{summary['borrow_value_eur']:.2f}",
            disclaimer=DISCLAIMER,
        ),
        encoding="utf-8",
    )
    return target


def write_provenance_page(
    db: sqlite3.Connection,
    txid: str,
    vout: int,
    price_at: Callable[[datetime.date], Decimal],
    current_price_eur: Decimal,
    as_of: datetime.date,
    out_dir: str | Path,
    max_depth: int = 100,
) -> Path:
    """Render the chain-of-custody page for ``txid:vout`` into ``out_dir``."""
    from utxoproof.advisory import analyze_utxo
    from utxoproof.kyc import propagate_graph, seed_source_kyc
    from utxoproof.provenance import build_provenance_chain, db_get_output

    seed_source_kyc(db)
    propagate_graph(db)
    steps = build_provenance_chain(txid, vout, db, price_at, max_depth)
    if not steps:
        raise ValueError(f"UTXO {txid}:{vout} not found")
    first, selected = steps[0], steps[-1]
    days_held = (as_of - first.block_time.date()).days
    current_value = selected.amount_btc * current_price_eur
    advisory = analyze_utxo(
        txid,
        vout,
        selected.amount_btc,
        first.block_time.date(),
        first.eur_value,
        current_value,
        selected.kyc_status,
        selected.kyc_fraction,
        as_of,
    )
    branches = []
    for step in steps:
        if len(step.parent_utxos) > 1:
            for parent in step.parent_utxos:
                row = db_get_output(db, parent[0], parent[1])
                if row is None:
                    continue
                branches.append(
                    {
                        "step": step.step_number,
                        "utxo": f"{parent[0]}:{parent[1]}",
                        "btc": f"{Decimal(row['value_sat']) / Decimal(100_000_000):.8f}",
                        "kyc": row["kyc_status"],
                    }
                )
    template = jinja2.Environment(autoescape=True).from_string(
        (Path(__file__).parent / "templates" / "provenance.html.j2").read_text(encoding="utf-8")
    )
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    target = out / f"provenance_{txid}_{vout}.html"
    target.write_text(
        template.render(
            txid=txid,
            vout=vout,
            amount_btc=f"{selected.amount_btc:.8f}",
            current_value_eur=f"{current_value:.2f}",
            current_price_eur=f"{current_price_eur:.2f}",
            kyc_status=selected.kyc_status,
            kyc_fraction=f"{selected.kyc_fraction:.0%}",
            days_held=days_held,
            flags=",".join(sorted(f.value for f in advisory.flags)),
            steps=[
                {
                    "n": s.step_number,
                    "date": s.block_time.date().isoformat(),
                    "block": s.block_height if s.block_height is not None else "—",
                    "event": s.event_description,
                    "btc": f"{s.amount_btc:.8f}",
                    "eur_price": f"{s.eur_price:.2f}",
                    "eur_value": f"{s.eur_value:.2f}",
                    "kyc": s.kyc_status,
                    "evidence": s.source_evidence or s.txid,
                    "mixing": s.mixing_event,
                }
                for s in steps
            ],
            branches=branches,
            evidence=sorted({s.source_evidence for s in steps if s.source_evidence}),
            disclaimer=DISCLAIMER,
        ),
        encoding="utf-8",
    )
    return target
